name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.2, 7.3, 7.4 ]
    steps:
      - uses: actions/checkout@v3
      - name: PHP Version
        run: php --version
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run test suite
        run: php ./vendor/bin/phpunit tests
